version: 2
references:
  nodejs_defaults: &nodejs_defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:carbon

jobs:
  checkout_code:
    <<: *nodejs_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build:
    <<: *nodejs_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: dependency-cache-{{ checksum "~/repo/package.json" }}
      - run:
          name: Install node dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "~/repo/package.json" }}
          paths:
            - ~/repo
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: "Set up npm auth token"
          command: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      - run:
          name: "Deploy image to npm"
          command: npm publish

  test:
    <<: *nodejs_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: yarn test

  lint:
    <<: *nodejs_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run eslint
          command: yarn eslint


  test-version:
    <<: *nodejs_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run version test
          command: yarn test:version

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - test-version:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test-version
            - test
            - build
          filters:
            branches:
              only:
                - master
