version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon

    steps:
      - checkout
      - run:
          name: "Set up npm auth token"
          command: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      - run:
          name: "Deploy image to npm"
          command: npm publish

  test-version:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: Run version test
          command: yarn test:version

workflows:
  version: 2

  build:
    jobs:
      - test-version
      - build:
          requires:
            - test-version
          filters:
            branches:
              only:
                - master